#ifndef MODEL_H
#define MODEL_H

#define MATERIAL_FILENAME_MAX (64)

typedef struct MaterialFile_tag
{
	char filename[MATERIAL_FILENAME_MAX]; // テクスチャファイル名

} MaterialFile;

// テクスチャ管理番号
typedef enum
{
	INDEX_MODEL_HERI_HONTAI,
	INDEX_MODEL_HERI_PUROPERA,
	INDEX_MODEL_DISH,
	INDEX_MODEL_COFFEE_CUP_BLUE,
	INDEX_MODEL_COFFEE_CUP_MIDORI,
	INDEX_MODEL_COFFEE_CUP_KIIRO,
	INDEX_MODEL_KING,
	INDEX_MODEL_GAITOU,
	INDEX_MODEL_ISU,
	INDEX_MODEL_JUSTAWAY_HEAD,
	INDEX_MODEL_JUSTAWAY_BODY,
	INDEX_MODEL_JUSTAWAY_RIGHTARM,
	INDEX_MODEL_JUSTAWAY_LEFTARM,
	INDEX_MODEL_TRAMPORINE_MAIN,
	INDEX_MODEL_SOUKOUSYA_BODY,
	INDEX_MODEL_SOUKOUSYA_SYASHI,
	INDEX_MODEL_SOUKOUSYA_TAIYA,
	INDEX_MODEL_SOUKOUSYA_TAIYA2,
	INDEX_MODEL_SOUKOUSYA_TAIYA3,
	INDEX_MODEL_SOUKOUSYA_TAIYA4,
	INDEX_MODEL_SOUKOUSYA_KIJU_DODAI,
	INDEX_MODEL_SOUKOUSYA_KIJU,
	INDEX_MODEL_SOUKOUSYA1_BODY,
	INDEX_MODEL_SOUKOUSYA1_HOUDAI,
	INDEX_MODEL_SOUKOUSYA1_HOUDAI_DODAI,
	INDEX_MODEL_SOUKOUSYA1_KIJU,
	INDEX_MODEL_SOUKOUSYA1_TAIYA,
	INDEX_MODEL_MARU,
	INDEX_MODEL_ENTYU,
	INDEX_MODEL_TYOUHOUKEI,
	INDEX_MODEL_HANA,
	INDEX_MODEL_YUREI,
	INDEX_MODEL_TEST,
	INDEX_MODEL_WALL,
	INDEX_MODEL_CHARA_HEAD,
	INDEX_MODEL_CHARA_BODY,
	INDEX_MODEL_CHARA_HAND,
	INDEX_MODEL_CHARA_LEG,

	INDEX_MODEL_ENEMY_HEAD,
	INDEX_MODEL_ENEMY_BODY,
	INDEX_MODEL_ENEMY_HAND,
	INDEX_MODEL_ENEMY_LEG,
	INDEX_MODEL_ENEMY_COA,


	INDEX_MODEL_MAX,

}MaterialIndex;

void Model_Xfile_Load(int index);
void Model_Draw(int index);				//複数化したらindexに　行列入れられたら便利
void Model_Finalise(int index);			//モデルデータの解放、破棄　複数化したらindexに

#endif // !MODEL_H
